name: app

type: php:8.2

build:
    flavor: composer

hooks:
    build: |
        composer install --no-dev --prefer-dist --no-scripts --no-interaction

    deploy: |
        php bin/console doctrine:migrations:migrate --no-interaction || true
        php bin/console cache:clear || true

runtime:
    extensions:
        - pdo_mysql

web:
    commands:
        start: php -S 0.0.0.0:8080 -t public

mounts:
    "/public/uploads": "shared:files"

disk: 512

relationships:
    database: "mariadb:mariadb"

variables:
    env:
        APP_ENV: "prod"
        APP_SECRET: "changeme"
        DATABASE_URL: "mysql://app:!ChangeMe!@database.internal/app"
