version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: '!ChangeMe!'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/va###> doctrinevolumes:
  db_data:
:
